# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1858351e9ceeb984f6d88a9c90b5b32d0d244c874ae94f5b57f79cbf94a8c667c5941c496ce3667b0dbea58f86078ab21c7f1eba2d832d23f3e8a96f402cc029

test:
  secret_key_base: fd4b4c7ed8f310d4dca620790591943cf6ad90ed9290923b05407c1e54babd91cc48d51e6b4208a90107fa353d903c1a3120835286a92415ec272e02050a7a13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
